import { ThemeId, VoucherTheme } from "@/types/voucher";

export const THEMES: Record<ThemeId, VoucherTheme> = {
  retro: {
    id: "retro",
    name: "Retro Ticket",
    emoji: "🎟️",
    description: "Vé xé cổ điển, vintage",
    bgColor: "#FFF8E7",
    bgGradient: "linear-gradient(135deg, #FFF8E7 0%, #FFE4B5 100%)",
    textColor: "#3D2B1F",
    accentColor: "#D4820A",
    borderStyle: "border-4 border-dashed border-amber-600",
    fontClass: "font-mono",
  },
  luxury: {
    id: "luxury",
    name: "Luxury Card",
    emoji: "💎",
    description: "Sang trọng, gold foil",
    bgColor: "#1A1A2E",
    bgGradient: "linear-gradient(135deg, #1A1A2E 0%, #16213E 100%)",
    textColor: "#F5E6C8",
    accentColor: "#FFD700",
    borderStyle: "border-2 border-yellow-400",
    fontClass: "font-serif",
  },
  cute: {
    id: "cute",
    name: "Cute Cartoon",
    emoji: "🌸",
    description: "Pastel dễ thương",
    bgColor: "#FFF0F5",
    bgGradient: "linear-gradient(135deg, #FFF0F5 0%, #FFE4F0 100%)",
    textColor: "#9B2C5A",
    accentColor: "#FF69B4",
    borderStyle: "border-4 border-pink-300 rounded-3xl",
    fontClass: "font-display",
  },
  minimal: {
    id: "minimal",
    name: "Minimalist",
    emoji: "◻️",
    description: "Trắng đen, typography",
    bgColor: "#FFFFFF",
    bgGradient: "linear-gradient(135deg, #FFFFFF 0%, #F8F8F8 100%)",
    textColor: "#1A1A1A",
    accentColor: "#1A1A1A",
    borderStyle: "border border-gray-900",
    fontClass: "font-sans",
  },
  y2k: {
    id: "y2k",
    name: "Y2K Vibes",
    emoji: "✨",
    description: "Holographic, pixel",
    bgColor: "#E8D5FF",
    bgGradient: "linear-gradient(135deg, #E8D5FF 0%, #C8B4FF 50%, #A8EDFF 100%)",
    textColor: "#2D0080",
    accentColor: "#8B00FF",
    borderStyle: "border-4 border-purple-400",
    fontClass: "font-display",
  },
  nature: {
    id: "nature",
    name: "Nature",
    emoji: "🌿",
    description: "Lá cây xanh mát",
    bgColor: "#F0FFF4",
    bgGradient: "linear-gradient(135deg, #F0FFF4 0%, #E6FFED 100%)",
    textColor: "#1A4731",
    accentColor: "#2E7D52",
    borderStyle: "border-4 border-green-600 rounded-2xl",
    fontClass: "font-sans",
  },
  neon: {
    id: "neon",
    name: "Neon Night",
    emoji: "⚡",
    description: "Dark mode, neon glow",
    bgColor: "#0D0D1A",
    bgGradient: "linear-gradient(135deg, #0D0D1A 0%, #1A0030 100%)",
    textColor: "#E0E0FF",
    accentColor: "#00FFCC",
    borderStyle: "border-2 border-cyan-400",
    fontClass: "font-display",
  },
  polaroid: {
    id: "polaroid",
    name: "Polaroid",
    emoji: "📸",
    description: "Ảnh phim cổ điển",
    bgColor: "#FFFEF0",
    bgGradient: "linear-gradient(135deg, #FFFEF0 0%, #FFFDE0 100%)",
    textColor: "#2C2C2C",
    accentColor: "#E63946",
    borderStyle: "border-8 border-white shadow-2xl",
    fontClass: "font-mono",
  },
  birthday: {
    id: "birthday",
    name: "Birthday",
    emoji: "🎂",
    description: "Sinh nhật rực rỡ",
    bgColor: "#FFF5F0",
    bgGradient: "linear-gradient(135deg, #FFF5F0 0%, #FFEEDD 100%)",
    textColor: "#7B2D00",
    accentColor: "#FF6600",
    borderStyle: "border-4 border-orange-400 rounded-3xl",
    fontClass: "font-display",
  },
};

export function getTheme(id: ThemeId): VoucherTheme {
  return THEMES[id] ?? THEMES.retro;
}
